/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrialRouteImport } from './routes/_authenticated/trial'
import { Route as AuthenticatedRaceSkillsRouteImport } from './routes/_authenticated/race-skills'
import { Route as AuthenticatedQuestsRouteImport } from './routes/_authenticated/quests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPenaltyZoneRouteImport } from './routes/_authenticated/penalty-zone'
import { Route as AuthenticatedIslandRouteImport } from './routes/_authenticated/island'
import { Route as AuthenticatedGuildRouteImport } from './routes/_authenticated/guild'
import { Route as AuthenticatedFusionRouteImport } from './routes/_authenticated/fusion'
import { Route as AuthenticatedForgeRouteImport } from './routes/_authenticated/forge'
import { Route as AuthenticatedExpeditionsRouteImport } from './routes/_authenticated/expeditions'
import { Route as AuthenticatedCrossFusionRouteImport } from './routes/_authenticated/cross-fusion'
import { Route as AuthenticatedCompendiumRouteImport } from './routes/_authenticated/compendium'
import { Route as AuthenticatedCodexRouteImport } from './routes/_authenticated/codex'
import { Route as AuthenticatedBazaarRouteImport } from './routes/_authenticated/bazaar'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as AuthenticatedAltarRouteImport } from './routes/_authenticated/altar'
import { Route as AuthenticatedAkashicRecordsRouteImport } from './routes/_authenticated/akashic-records'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrialRoute = AuthenticatedTrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRaceSkillsRoute = AuthenticatedRaceSkillsRouteImport.update({
  id: '/race-skills',
  path: '/race-skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestsRoute = AuthenticatedQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenaltyZoneRoute =
  AuthenticatedPenaltyZoneRouteImport.update({
    id: '/penalty-zone',
    path: '/penalty-zone',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIslandRoute = AuthenticatedIslandRouteImport.update({
  id: '/island',
  path: '/island',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuildRoute = AuthenticatedGuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFusionRoute = AuthenticatedFusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForgeRoute = AuthenticatedForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpeditionsRoute =
  AuthenticatedExpeditionsRouteImport.update({
    id: '/expeditions',
    path: '/expeditions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrossFusionRoute =
  AuthenticatedCrossFusionRouteImport.update({
    id: '/cross-fusion',
    path: '/cross-fusion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompendiumRoute = AuthenticatedCompendiumRouteImport.update({
  id: '/compendium',
  path: '/compendium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodexRoute = AuthenticatedCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBazaarRoute = AuthenticatedBazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAltarRoute = AuthenticatedAltarRouteImport.update({
  id: '/altar',
  path: '/altar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkashicRecordsRoute =
  AuthenticatedAkashicRecordsRouteImport.update({
    id: '/akashic-records',
    path: '/akashic-records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/akashic-records': typeof AuthenticatedAkashicRecordsRoute
  '/altar': typeof AuthenticatedAltarRoute
  '/battle': typeof AuthenticatedBattleRoute
  '/bazaar': typeof AuthenticatedBazaarRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/compendium': typeof AuthenticatedCompendiumRoute
  '/cross-fusion': typeof AuthenticatedCrossFusionRoute
  '/expeditions': typeof AuthenticatedExpeditionsRoute
  '/forge': typeof AuthenticatedForgeRoute
  '/fusion': typeof AuthenticatedFusionRoute
  '/guild': typeof AuthenticatedGuildRoute
  '/island': typeof AuthenticatedIslandRoute
  '/penalty-zone': typeof AuthenticatedPenaltyZoneRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/race-skills': typeof AuthenticatedRaceSkillsRoute
  '/trial': typeof AuthenticatedTrialRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/akashic-records': typeof AuthenticatedAkashicRecordsRoute
  '/altar': typeof AuthenticatedAltarRoute
  '/battle': typeof AuthenticatedBattleRoute
  '/bazaar': typeof AuthenticatedBazaarRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/compendium': typeof AuthenticatedCompendiumRoute
  '/cross-fusion': typeof AuthenticatedCrossFusionRoute
  '/expeditions': typeof AuthenticatedExpeditionsRoute
  '/forge': typeof AuthenticatedForgeRoute
  '/fusion': typeof AuthenticatedFusionRoute
  '/guild': typeof AuthenticatedGuildRoute
  '/island': typeof AuthenticatedIslandRoute
  '/penalty-zone': typeof AuthenticatedPenaltyZoneRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/race-skills': typeof AuthenticatedRaceSkillsRoute
  '/trial': typeof AuthenticatedTrialRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/akashic-records': typeof AuthenticatedAkashicRecordsRoute
  '/_authenticated/altar': typeof AuthenticatedAltarRoute
  '/_authenticated/battle': typeof AuthenticatedBattleRoute
  '/_authenticated/bazaar': typeof AuthenticatedBazaarRoute
  '/_authenticated/codex': typeof AuthenticatedCodexRoute
  '/_authenticated/compendium': typeof AuthenticatedCompendiumRoute
  '/_authenticated/cross-fusion': typeof AuthenticatedCrossFusionRoute
  '/_authenticated/expeditions': typeof AuthenticatedExpeditionsRoute
  '/_authenticated/forge': typeof AuthenticatedForgeRoute
  '/_authenticated/fusion': typeof AuthenticatedFusionRoute
  '/_authenticated/guild': typeof AuthenticatedGuildRoute
  '/_authenticated/island': typeof AuthenticatedIslandRoute
  '/_authenticated/penalty-zone': typeof AuthenticatedPenaltyZoneRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quests': typeof AuthenticatedQuestsRoute
  '/_authenticated/race-skills': typeof AuthenticatedRaceSkillsRoute
  '/_authenticated/trial': typeof AuthenticatedTrialRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/akashic-records'
    | '/altar'
    | '/battle'
    | '/bazaar'
    | '/codex'
    | '/compendium'
    | '/cross-fusion'
    | '/expeditions'
    | '/forge'
    | '/fusion'
    | '/guild'
    | '/island'
    | '/penalty-zone'
    | '/profile'
    | '/quests'
    | '/race-skills'
    | '/trial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/akashic-records'
    | '/altar'
    | '/battle'
    | '/bazaar'
    | '/codex'
    | '/compendium'
    | '/cross-fusion'
    | '/expeditions'
    | '/forge'
    | '/fusion'
    | '/guild'
    | '/island'
    | '/penalty-zone'
    | '/profile'
    | '/quests'
    | '/race-skills'
    | '/trial'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/akashic-records'
    | '/_authenticated/altar'
    | '/_authenticated/battle'
    | '/_authenticated/bazaar'
    | '/_authenticated/codex'
    | '/_authenticated/compendium'
    | '/_authenticated/cross-fusion'
    | '/_authenticated/expeditions'
    | '/_authenticated/forge'
    | '/_authenticated/fusion'
    | '/_authenticated/guild'
    | '/_authenticated/island'
    | '/_authenticated/penalty-zone'
    | '/_authenticated/profile'
    | '/_authenticated/quests'
    | '/_authenticated/race-skills'
    | '/_authenticated/trial'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trial': {
      id: '/_authenticated/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof AuthenticatedTrialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/race-skills': {
      id: '/_authenticated/race-skills'
      path: '/race-skills'
      fullPath: '/race-skills'
      preLoaderRoute: typeof AuthenticatedRaceSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quests': {
      id: '/_authenticated/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedQuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penalty-zone': {
      id: '/_authenticated/penalty-zone'
      path: '/penalty-zone'
      fullPath: '/penalty-zone'
      preLoaderRoute: typeof AuthenticatedPenaltyZoneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/island': {
      id: '/_authenticated/island'
      path: '/island'
      fullPath: '/island'
      preLoaderRoute: typeof AuthenticatedIslandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guild': {
      id: '/_authenticated/guild'
      path: '/guild'
      fullPath: '/guild'
      preLoaderRoute: typeof AuthenticatedGuildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fusion': {
      id: '/_authenticated/fusion'
      path: '/fusion'
      fullPath: '/fusion'
      preLoaderRoute: typeof AuthenticatedFusionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forge': {
      id: '/_authenticated/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AuthenticatedForgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expeditions': {
      id: '/_authenticated/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof AuthenticatedExpeditionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cross-fusion': {
      id: '/_authenticated/cross-fusion'
      path: '/cross-fusion'
      fullPath: '/cross-fusion'
      preLoaderRoute: typeof AuthenticatedCrossFusionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compendium': {
      id: '/_authenticated/compendium'
      path: '/compendium'
      fullPath: '/compendium'
      preLoaderRoute: typeof AuthenticatedCompendiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/codex': {
      id: '/_authenticated/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof AuthenticatedCodexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bazaar': {
      id: '/_authenticated/bazaar'
      path: '/bazaar'
      fullPath: '/bazaar'
      preLoaderRoute: typeof AuthenticatedBazaarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/altar': {
      id: '/_authenticated/altar'
      path: '/altar'
      fullPath: '/altar'
      preLoaderRoute: typeof AuthenticatedAltarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akashic-records': {
      id: '/_authenticated/akashic-records'
      path: '/akashic-records'
      fullPath: '/akashic-records'
      preLoaderRoute: typeof AuthenticatedAkashicRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAkashicRecordsRoute: typeof AuthenticatedAkashicRecordsRoute
  AuthenticatedAltarRoute: typeof AuthenticatedAltarRoute
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRoute
  AuthenticatedBazaarRoute: typeof AuthenticatedBazaarRoute
  AuthenticatedCodexRoute: typeof AuthenticatedCodexRoute
  AuthenticatedCompendiumRoute: typeof AuthenticatedCompendiumRoute
  AuthenticatedCrossFusionRoute: typeof AuthenticatedCrossFusionRoute
  AuthenticatedExpeditionsRoute: typeof AuthenticatedExpeditionsRoute
  AuthenticatedForgeRoute: typeof AuthenticatedForgeRoute
  AuthenticatedFusionRoute: typeof AuthenticatedFusionRoute
  AuthenticatedGuildRoute: typeof AuthenticatedGuildRoute
  AuthenticatedIslandRoute: typeof AuthenticatedIslandRoute
  AuthenticatedPenaltyZoneRoute: typeof AuthenticatedPenaltyZoneRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestsRoute: typeof AuthenticatedQuestsRoute
  AuthenticatedRaceSkillsRoute: typeof AuthenticatedRaceSkillsRoute
  AuthenticatedTrialRoute: typeof AuthenticatedTrialRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAkashicRecordsRoute: AuthenticatedAkashicRecordsRoute,
  AuthenticatedAltarRoute: AuthenticatedAltarRoute,
  AuthenticatedBattleRoute: AuthenticatedBattleRoute,
  AuthenticatedBazaarRoute: AuthenticatedBazaarRoute,
  AuthenticatedCodexRoute: AuthenticatedCodexRoute,
  AuthenticatedCompendiumRoute: AuthenticatedCompendiumRoute,
  AuthenticatedCrossFusionRoute: AuthenticatedCrossFusionRoute,
  AuthenticatedExpeditionsRoute: AuthenticatedExpeditionsRoute,
  AuthenticatedForgeRoute: AuthenticatedForgeRoute,
  AuthenticatedFusionRoute: AuthenticatedFusionRoute,
  AuthenticatedGuildRoute: AuthenticatedGuildRoute,
  AuthenticatedIslandRoute: AuthenticatedIslandRoute,
  AuthenticatedPenaltyZoneRoute: AuthenticatedPenaltyZoneRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestsRoute: AuthenticatedQuestsRoute,
  AuthenticatedRaceSkillsRoute: AuthenticatedRaceSkillsRoute,
  AuthenticatedTrialRoute: AuthenticatedTrialRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
