-- ────────────────────────────────────────────────────────────────────────────
-- Seed: First 150 bestiary monsters (the ones with images).
-- Idempotent: wipes all monsters + dependent gameplay rows, reseeds 1..150.
-- Re-run after every art-batch threshold (200, 250, 300, ...) with the
-- bestiary_id range bumped accordingly.
-- ────────────────────────────────────────────────────────────────────────────

BEGIN;

-- 1. Clear gameplay rows that FK into monsters (preserve banners, profiles, tasks)
DELETE FROM public.user_monsters;
DELETE FROM public.pulls;
DELETE FROM public.fusion_recipes;
UPDATE public.banners SET featured_monster_id = NULL;

-- 2. Wipe monsters
DELETE FROM public.monsters;

-- 3. Insert first 150 monsters
INSERT INTO public.monsters (bestiary_id, release_set, realm_id, name, rarity, role, element, base_hp, base_atk, base_def, base_spd, is_ex) VALUES
(1, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Lightning Dark Angel', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 200, 113, 40, 28, 'false'),
(2, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Pawn Cursed', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Arcane', 110, 24, 20, 13, 'false'),
(3, 1, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Knotted Vampire Thrall Awakened', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Dread', 135, 41, 30, 21, 'false'),
(4, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Jade Undead Giant', 'rare'::public.monster_rarity, 'healer'::public.monster_role, 'Death', 300, 53, 55, 28, 'false'),
(5, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Twilight Templar Champion', 'rare'::public.monster_rarity, 'tank'::public.monster_role, 'Divine', 375, 45, 75, 20, 'false'),
(6, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Crystal Reaper Unit', 'rare'::public.monster_rarity, 'debuffer'::public.monster_role, 'Stellar', 225, 68, 50, 35, 'false'),
(7, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Marrow Knight Beta', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Death', 165, 36, 30, 20, 'false'),
(8, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Fallen Abyssal Knight', 'epic'::public.monster_rarity, 'tank'::public.monster_role, 'Death', 750, 90, 150, 40, 'false'),
(9, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Siege Taken Champion', 'elite'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 280, 158, 56, 39, 'false'),
(10, 1, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Twilight Stormvermin', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Chaos', 165, 36, 30, 20, 'false'),
(11, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Torn Shadow Fragment I', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Void', 150, 18, 30, 8, 'false'),
(12, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Prime Deep One Archpriest', 'elite'::public.monster_rarity, 'support'::public.monster_role, 'Void', 385, 84, 70, 46, 'false'),
(13, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Grim Chosen Acolyte Elite', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 80, 45, 16, 11, 'false'),
(14, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Byakhee Rider Minor', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Void', 135, 41, 30, 21, 'false'),
(15, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Cave Slime Junior', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 80, 45, 16, 11, 'false'),
(16, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Mangy Chaos Fragment', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Void', 80, 45, 16, 11, 'false'),
(17, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Cataclysm Ancient Green Dragon', 'epic'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 400, 225, 80, 55, 'false'),
(18, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Void Predator Hunter', 'rare'::public.monster_rarity, 'support'::public.monster_role, 'Stellar', 275, 60, 50, 33, 'false'),
(19, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Charred Corpse IV', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Death', 150, 18, 30, 8, 'false'),
(20, 1, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Cave Spider Minor', 'uncommon'::public.monster_rarity, 'tank'::public.monster_role, 'Nature', 225, 27, 45, 12, 'false'),
(21, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Primordial Golem', 'rare'::public.monster_rarity, 'debuffer'::public.monster_role, 'Arcane', 225, 68, 50, 35, 'false'),
(22, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Cursed Ash Knight Junior', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 120, 68, 24, 17, 'false'),
(23, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Archon FFXIV Elite', 'elite'::public.monster_rarity, 'debuffer'::public.monster_role, 'Primal', 315, 95, 70, 49, 'false'),
(24, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Infernal Crota Son Scout', 'epic'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 400, 225, 80, 55, 'false'),
(25, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Siege Xenomorph Praetorian', 'elite'::public.monster_rarity, 'tank'::public.monster_role, 'Stellar', 525, 63, 105, 28, 'false'),
(26, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Elder Arcane Golem', 'elite'::public.monster_rarity, 'healer'::public.monster_role, 'Arcane', 420, 74, 77, 39, 'false'),
(27, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Crimson Void Crawler Prime', 'uncommon'::public.monster_rarity, 'healer'::public.monster_role, 'Void', 180, 31, 33, 17, 'false'),
(28, 1, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Dim Cave Bat', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Dread', 150, 18, 30, 8, 'false'),
(29, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Plague Zombie', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 80, 45, 16, 11, 'false'),
(30, 1, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Madman', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Chaos', 80, 45, 16, 11, 'false'),
(31, 1, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Pitted Cave Bear Awakened', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Nature', 120, 68, 24, 17, 'false'),
(32, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Weedy Web Crawler', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Digital', 110, 24, 20, 13, 'false'),
(33, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Cataclysm Leviathan Sea', 'epic'::public.monster_rarity, 'support'::public.monster_role, 'Divine', 550, 120, 100, 65, 'false'),
(34, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Mottled Chapel Priest Minor', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 80, 45, 16, 11, 'false'),
(35, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Fetid Bone Knight Awakened', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Death', 165, 36, 30, 20, 'false'),
(36, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Holy Guard', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Divine', 150, 18, 30, 8, 'false'),
(37, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Cursed Star Spawn Priest', 'rare'::public.monster_rarity, 'healer'::public.monster_role, 'Void', 300, 53, 55, 28, 'false'),
(38, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Grimy Warped Hermit Senior', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Void', 110, 24, 20, 13, 'false'),
(39, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Forbidden Gug Alpha', 'epic'::public.monster_rarity, 'healer'::public.monster_role, 'Void', 600, 105, 110, 55, 'false'),
(40, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Fell Divine Acolyte Greater', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Divine', 150, 18, 30, 8, 'false'),
(41, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Bristled Cosmic Crawler', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Void', 135, 41, 30, 21, 'false'),
(42, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Infernal Xenomorph Drone', 'rare'::public.monster_rarity, 'support'::public.monster_role, 'Stellar', 275, 60, 50, 33, 'false'),
(43, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Troll Common IV', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Primal', 150, 18, 30, 8, 'false'),
(44, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Bristled Vex Hobgoblin Omega', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 120, 68, 24, 17, 'false'),
(45, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Rust Grave Knight II', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 120, 68, 24, 17, 'false'),
(46, 1, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Scraped Zombie Farmer', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Dread', 80, 45, 16, 11, 'false'),
(47, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Alien Worm Elite', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Stellar', 150, 18, 30, 8, 'false'),
(48, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Night Stalker Beta', 'uncommon'::public.monster_rarity, 'healer'::public.monster_role, 'Void', 180, 31, 33, 17, 'false'),
(49, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Squalid Reaper Grot Senior', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 80, 45, 16, 11, 'false'),
(50, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Fell Cosmic Bat', 'common'::public.monster_rarity, 'healer'::public.monster_role, 'Stellar', 120, 21, 22, 11, 'false'),
(51, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Bleak Church Acolyte Minor', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Divine', 110, 24, 20, 13, 'false'),
(52, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Knotted Naga Common Greater', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Primal', 135, 41, 30, 21, 'false'),
(53, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Squalid Data Rat Elite', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Digital', 80, 45, 16, 11, 'false'),
(54, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Abyss Shadow Angel', 'rare'::public.monster_rarity, 'support'::public.monster_role, 'Divine', 275, 60, 50, 33, 'false'),
(55, 1, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Sunken Wrecker III', 'common'::public.monster_rarity, 'debuffer'::public.monster_role, 'Chaos', 90, 27, 20, 14, 'false'),
(56, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'World The Witness Final Shape', 'ex'::public.monster_rarity, 'tank'::public.monster_role, 'Stellar', 3000, 360, 600, 160, 'true'),
(57, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Giant Banshee', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 200, 113, 40, 28, 'false'),
(58, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Small White Slime VII', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 80, 45, 16, 11, 'false'),
(59, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Dark Tendril Feral', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Void', 150, 18, 30, 8, 'false'),
(60, 1, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Dingy Frost Bug Prime', 'common'::public.monster_rarity, 'debuffer'::public.monster_role, 'Nature', 90, 27, 20, 14, 'false'),
(61, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Scrawny WoW Murloc Greater', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 80, 45, 16, 11, 'false'),
(62, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Gnawed Naga Common Minor', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 120, 68, 24, 17, 'false'),
(63, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Ancient Grave Warden', 'rare'::public.monster_rarity, 'tank'::public.monster_role, 'Death', 375, 45, 75, 20, 'false'),
(64, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Lesser Code Goblin Omega', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Digital', 150, 18, 30, 8, 'false'),
(65, 1, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Swamp Bear', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Nature', 165, 36, 30, 20, 'false'),
(66, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Cataclysm Dracolich Elder', 'epic'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 400, 225, 80, 55, 'false'),
(67, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Specter', 'uncommon'::public.monster_rarity, 'tank'::public.monster_role, 'Arcane', 225, 27, 45, 12, 'false'),
(68, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Titan Corrupted Knight', 'rare'::public.monster_rarity, 'debuffer'::public.monster_role, 'Death', 225, 68, 50, 35, 'false'),
(69, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Spindly Chapel Priest II', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 80, 45, 16, 11, 'false'),
(70, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Prime Geth Prime', 'elite'::public.monster_rarity, 'tank'::public.monster_role, 'Stellar', 525, 63, 105, 28, 'false'),
(71, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Withered Glitch Rat Greater', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Digital', 150, 18, 30, 8, 'false'),
(72, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Titan Grave Warden', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 200, 113, 40, 28, 'false'),
(73, 1, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Twisted Banshee Wail', 'uncommon'::public.monster_rarity, 'healer'::public.monster_role, 'Dread', 180, 31, 33, 17, 'false'),
(74, 1, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Dire Rock Drake', 'rare'::public.monster_rarity, 'debuffer'::public.monster_role, 'Nature', 225, 68, 50, 35, 'false'),
(75, 1, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Brine Apparition', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Dread', 120, 68, 24, 17, 'false'),
(76, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Pack Binary Rat II', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Digital', 80, 45, 16, 11, 'false'),
(77, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Demon Black Frost', 'rare'::public.monster_rarity, 'tank'::public.monster_role, 'Digital', 375, 45, 75, 20, 'false'),
(78, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Forest Critter Awakened', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 80, 45, 16, 11, 'false'),
(79, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Star Bat', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 80, 45, 16, 11, 'false'),
(80, 1, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Undying Mind Flayer', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 200, 113, 40, 28, 'false'),
(81, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Slime Temple Guard Ancient', 'common'::public.monster_rarity, 'debuffer'::public.monster_role, 'Divine', 90, 27, 20, 14, 'false'),
(82, 1, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Haggard Brute', 'common'::public.monster_rarity, 'healer'::public.monster_role, 'Chaos', 120, 21, 22, 11, 'false'),
(83, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Dream Stalker V', 'uncommon'::public.monster_rarity, 'tank'::public.monster_role, 'Void', 225, 27, 45, 12, 'false'),
(84, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Squalid Cursed Pilgrim Senior', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Death', 110, 24, 20, 13, 'false'),
(85, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Rusted Hollow Feral', 'common'::public.monster_rarity, 'debuffer'::public.monster_role, 'Death', 90, 27, 20, 14, 'false'),
(86, 1, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Slime Digital Greater', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Digital', 120, 68, 24, 17, 'false'),
(87, 1, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Squalid Brawler Tamed', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Chaos', 80, 45, 16, 11, 'false'),
(88, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Slime Knight', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Primal', 135, 41, 30, 21, 'false'),
(89, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Swamp Undead Pilgrim Young', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Death', 110, 24, 20, 13, 'false'),
(90, 1, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Apocalypse Old God Fragment', 'epic'::public.monster_rarity, 'tank'::public.monster_role, 'Primal', 750, 90, 150, 40, 'false'),
(91, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Primordial Zoth-Ommog Sunken', 'legendary'::public.monster_rarity, 'debuffer'::public.monster_role, 'Void', 720, 216, 160, 112, 'false'),
(92, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Arcane Fallen Captain', 'rare'::public.monster_rarity, 'support'::public.monster_role, 'Stellar', 275, 60, 50, 33, 'false'),
(93, 1, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Battle Flood Infection Blessed', 'uncommon'::public.monster_rarity, 'tank'::public.monster_role, 'Stellar', 225, 27, 45, 12, 'false'),
(94, 1, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Torn Zombie Farmer Blessed', 'common'::public.monster_rarity, 'debuffer'::public.monster_role, 'Dread', 90, 27, 20, 14, 'false'),
(95, 1, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Howling Paladin Champion', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 200, 113, 40, 28, 'false'),
(96, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Grand Knight Commander', 'elite'::public.monster_rarity, 'tank'::public.monster_role, 'Death', 525, 63, 105, 28, 'false'),
(97, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Bleached Skeleton Champion', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Death', 135, 41, 30, 21, 'false'),
(98, 1, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Nightgaunt', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Void', 135, 41, 30, 21, 'false'),
(99, 1, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Tar Cave Bat Junior', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Nature', 80, 45, 16, 11, 'false'),
(100, 1, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Ether Undead Dragon', 'rare'::public.monster_rarity, 'tank'::public.monster_role, 'Death', 375, 45, 75, 20, 'false'),
(101, 2, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Haze Earth Sprite Junior', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Divine', 165, 36, 30, 20, 'false'),
(102, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Skeleton Soldier I', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Death', 150, 18, 30, 8, 'false'),
(103, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Scarred Hollow Champion II', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 120, 68, 24, 17, 'false'),
(104, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Dark Dark Walker Tamed', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 80, 45, 16, 11, 'false'),
(105, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Royal Elder Brain', 'elite'::public.monster_rarity, 'support'::public.monster_role, 'Arcane', 385, 84, 70, 46, 'false'),
(106, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Scraggly Chewer', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Arcane', 150, 18, 30, 8, 'false'),
(107, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Ember Knight II', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Death', 165, 36, 30, 20, 'false'),
(108, 2, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Scourge Mi-Go Surgeon', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Void', 200, 113, 40, 28, 'false'),
(109, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Putrid Gray Slime', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 80, 45, 16, 11, 'false'),
(110, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Salt Yellow Slime', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Primal', 110, 24, 20, 13, 'false'),
(111, 2, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Gloom Banshee Sob', 'uncommon'::public.monster_rarity, 'debuffer'::public.monster_role, 'Dread', 135, 41, 30, 21, 'false'),
(112, 2, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Haunted Doll', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Dread', 80, 45, 16, 11, 'false'),
(113, 2, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Dreamer Greater', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Void', 80, 45, 16, 11, 'false'),
(114, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Lightning Displacer Beast', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 200, 113, 40, 28, 'false'),
(115, 2, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Marsh Corrupted Bit IV', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Digital', 80, 45, 16, 11, 'false'),
(116, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Spindly Lurker Ancient', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Arcane', 150, 18, 30, 8, 'false'),
(117, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Sorrow Drow', 'uncommon'::public.monster_rarity, 'tank'::public.monster_role, 'Arcane', 225, 27, 45, 12, 'false'),
(118, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'WoW Quilboar', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 80, 45, 16, 11, 'false'),
(119, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Gale Desert Guardian IV', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 120, 68, 24, 17, 'false'),
(120, 2, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Night Corrupt Scholar', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Void', 80, 45, 16, 11, 'false'),
(121, 2, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Quarried Fallen Vandal Prime', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 120, 68, 24, 17, 'false'),
(122, 2, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Murky Nebula Mote', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 80, 45, 16, 11, 'false'),
(123, 2, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Banshee Moan VI', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Dread', 120, 68, 24, 17, 'false'),
(124, 2, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Withered Berserker Beta', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Chaos', 150, 18, 30, 8, 'false'),
(125, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Zealous Elder Brain', 'elite'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 280, 158, 56, 39, 'false'),
(126, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Cinder Hollow Beta', 'common'::public.monster_rarity, 'debuffer'::public.monster_role, 'Death', 90, 27, 20, 14, 'false'),
(127, 2, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Absolute Hanami Forest Arms', 'legendary'::public.monster_rarity, 'healer'::public.monster_role, 'Dread', 960, 168, 176, 88, 'false'),
(128, 2, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Venom Space Pirate Warrior', 'uncommon'::public.monster_rarity, 'support'::public.monster_role, 'Stellar', 165, 36, 30, 20, 'false'),
(129, 2, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Soggy Bark Frog IV', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Nature', 150, 18, 30, 8, 'false'),
(130, 2, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Dusk Blessed Sprite Tamed', 'uncommon'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 120, 68, 24, 17, 'false'),
(131, 2, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Supreme Champion Digimon', 'elite'::public.monster_rarity, 'tank'::public.monster_role, 'Digital', 525, 63, 105, 28, 'false'),
(132, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Soul Mountain Spirit', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 200, 113, 40, 28, 'false'),
(133, 2, (SELECT id FROM public.realms WHERE name = 'Digital Nexus' LIMIT 1), 'Rune Street Wyrm', 'rare'::public.monster_rarity, 'support'::public.monster_role, 'Digital', 275, 60, 50, 33, 'false'),
(134, 2, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Dread Slaanesh Herald', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Chaos', 200, 113, 40, 28, 'false'),
(135, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Blood Tomb Warden', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 200, 113, 40, 28, 'false'),
(136, 2, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Cursed Temple Knight III', 'uncommon'::public.monster_rarity, 'healer'::public.monster_role, 'Divine', 180, 31, 33, 17, 'false'),
(137, 2, (SELECT id FROM public.realms WHERE name = 'Void Frontier' LIMIT 1), 'Star Grub Prime', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Stellar', 80, 45, 16, 11, 'false'),
(138, 2, (SELECT id FROM public.realms WHERE name = 'Blighted Expanse' LIMIT 1), 'Nightmare Ash Giant', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Death', 200, 113, 40, 28, 'false'),
(139, 2, (SELECT id FROM public.realms WHERE name = 'The Outer Dark' LIMIT 1), 'Flame Moon Beast Trader', 'rare'::public.monster_rarity, 'tank'::public.monster_role, 'Void', 375, 45, 75, 20, 'false'),
(140, 2, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Dingy Swamp Bat', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Nature', 80, 45, 16, 11, 'false'),
(141, 2, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Exalted Angel Champion', 'elite'::public.monster_rarity, 'attacker'::public.monster_role, 'Divine', 280, 158, 56, 39, 'false'),
(142, 2, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Immortal Lord of Change Minor', 'elite'::public.monster_rarity, 'healer'::public.monster_role, 'Chaos', 420, 74, 77, 39, 'false'),
(143, 2, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Wretched Plague Rat III', 'common'::public.monster_rarity, 'tank'::public.monster_role, 'Chaos', 150, 18, 30, 8, 'false'),
(144, 2, (SELECT id FROM public.realms WHERE name = 'Divine Threshold' LIMIT 1), 'Initiate Angel', 'common'::public.monster_rarity, 'support'::public.monster_role, 'Divine', 110, 24, 20, 13, 'false'),
(145, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Abyss WoW Kel''Thuzad Scout', 'rare'::public.monster_rarity, 'support'::public.monster_role, 'Primal', 275, 60, 50, 33, 'false'),
(146, 2, (SELECT id FROM public.realms WHERE name = 'Wild Frontier' LIMIT 1), 'Frost Bug Lesser', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Nature', 80, 45, 16, 11, 'false'),
(147, 2, (SELECT id FROM public.realms WHERE name = 'Ancient Vaults' LIMIT 1), 'Dragon Medusa', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Arcane', 200, 113, 40, 28, 'false'),
(148, 2, (SELECT id FROM public.realms WHERE name = 'Elder Realm' LIMIT 1), 'Titan Slime Stack Giant', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Primal', 200, 113, 40, 28, 'false'),
(149, 2, (SELECT id FROM public.realms WHERE name = 'Chaos Wastes' LIMIT 1), 'Dragon Chosen of Chaos', 'rare'::public.monster_rarity, 'attacker'::public.monster_role, 'Chaos', 200, 113, 40, 28, 'false'),
(150, 2, (SELECT id FROM public.realms WHERE name = 'Haunted Veil' LIMIT 1), 'Lesser Cursed Villager', 'common'::public.monster_rarity, 'attacker'::public.monster_role, 'Dread', 80, 45, 16, 11, 'false');

COMMIT;
